### ISSUE TITLE
Move past items (not done) to today

### ISSUE THREAD

**Issue by morris** [morris/vanilla-todo#14]
When (re-)loading the app, past items that were not marked "done" should automatically move to today so they don't get lost. This should be solvable by

- implementing the transition in `TodoLogic.js`, and
- and calling the transition on load in `TodoController.js`.

**Comment by harrisonJones12** [comment]
I have noticed an issue where the todo items do not have the correct date.
<img width="1680" alt="image" src="https://github.com/morris/vanilla-todo/assets/35752544/91537bf3-9c3f-4087-a48e-a93122ea0c20">
I have kind of worked out solution however my logic will not work due to dates of the saved todoItems being incorrect. I'll keep working on it. @morris

**Comment by morris** [comment]
Thanks for looking into it! Hmmm, unfortunately I can't reproduce the situation you're describing. Could it be a time zone issue?

**Comment by morris** [comment]
Indeed... should be fixed in `main` :)

**Comment by morris** [comment]
@harrisonJones12 any chance you want to pick this up again :)?
